routes/web.php
<?php

Route::get('kelas-online/showcase','KelasOnlineController@Showcase')->name('kelasonline.showcase');

Route::get('wisuda/2018','WisudaController@index')->name('wisuda');
	Route::post('wisuda/2018/store','WisudaController@store')->name('wisuda.store');
	Route::get('wisuda/2018/message/{status?}','WisudaController@message')->name('wisuda.message');
	Route::get('wisuda/absensi/{emailwisuda}','WisudaController@absensi')->name('wisuda.absensi');
	Route::get('wisuda/absensi/{emailwisuda}/store/{from?}','WisudaController@absensiStore')->name('wisuda.absensi.store');
	Route::get('wisuda/report','WisudaController@report')->name('wisuda.report');
	Route::get('wisuda/hadir','WisudaController@hadir')->name('wisuda.hadir');
	Route::get('wisuda/blast-undangan','WisudaController@blastUndanganWisuda');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// akses ke image sid card peserta
Route::get('/public/assets/upload_files/peserta/sid_card/{sid}', function($path) {
    $path = public_path('assets/upload_files/peserta/sid_card/').$path;

    $response = Response::make(
     File::get($path), 
     200
    );
    $response->header(
    'Content-type',
    'image/png'
    );
    return $response;
});
// akses ke image photo peserta
Route::get('/public/assets/upload_files/peserta/photos/{photos}', function($path) {
    $path = public_path('assets/upload_files/peserta/photos/').$path;

    $response = Response::make(
     File::get($path), 
     200
    );
    $response->header(
    'Content-type',
    'image/png'
    );
    return $response;
});
// akses ke ktp peserta
Route::get('/public/assets/upload_files/peserta/ktp/{ktp}', function($path) {
    $path = public_path('assets/upload_files/peserta/ktp/').$path;

    $response = Response::make(
     File::get($path), 
     200
    );
    $response->header(
    'Content-type',
    'image/png'
    );
    return $response;
});
Route::post('login', 'Auth\LoginController@authenticate')->name('login');
Route::get('/','HomeController@index')->name('home');



/*  if(date("Y-m-d H:i")<"2018-10-26 21:00" && date("Y-m-d H:i")>"2018-10-26 20:00") { 
	 Route::get('/','HomeController@maintenance')->name('home');
 }else{
	
	 Route::get('/','HomeController@index')->name('home');
 } */

Route::get('/','HomeController@index')->name('home');
Route::get('/home','HomeController@index')->name('home');
Route::get('/daftar-batch/{batchid}/{batchname}',"HomeController@pendaftaranDetail")->name('daftar.detail');
Route::post('batch/find','HomeController@search')->name('search');

/*
|--------------------------------------------------------------------------
| Forgot Password
|--------------------------------------------------------------------------
*/
Route::get('/forgot-password','HomeController@forgot_pasword')->name('forgot_password');
Route::get('/forgot-password-admisi','HomeController@forgot_pasword_admisi')->name('forgot_password_admisi');
Route::post('/forgot-password/proses', 'HomeController@forgot_pasword_proses')->name('forgotpassword.proses');
Route::get('reset-password/{useremail}/{userid}','HomeController@reset_password')->name('reset_password');
Route::post('reset-password/proses/{useremail}/{userid}','HomeController@reset_password_proses')->name('resetpassword.proses');

/*
|--------------------------------------------------------------------------
| Tentang Kami
|--------------------------------------------------------------------------
*/
Route::get('/profil-perusahaan','AboutUsController@profilPerusahaan')->name('profil-perusahaan');
Route::get('/visi-misi','AboutUsController@visiMisi')->name('visi-misi');
Route::get('/sejarah','AboutUsController@sejarah')->name('sejarah');
Route::get('/struktur','AboutUsController@struktur')->name('struktur');

/*
|--------------------------------------------------------------------------
| Produk dan Layanan ------------------------------------------------------
|--------------------------------------------------------------------------
| Sertifikasi Profesi
|--------------------------------------------------------------------------
*/
Route::get('/wppe','ProdukLayananController@wppeProduct')->name('wppe-product');
Route::get('/wmi','ProdukLayananController@wmiProduct')->name('wmi-product');
Route::get('/aspm','ProdukLayananController@aspmProduct')->name('aspm-product');
Route::get('/wpee','ProdukLayananController@wpeeProduct')->name('wpee-product');
Route::get('/syariah','ProdukLayananController@pdpms')->name('pdpms');
Route::get('/kerjasama-perguruan-tinggi','ProdukLayananController@kerjasamaPerguruanTinggi')->name('kerjasama-perguruan-tinggi');
/*
|--------------------------------------------------------------------------
| Data Pasar Modal
|--------------------------------------------------------------------------
*/
Route::get('/data-historis','ProdukLayananController@dataHistoris')->name('data-historis');
Route::get('/perpustakaan','ProdukLayananController@perpustakaan')->name('perpustakaan');
Route::get('/permintaan-data','ProdukLayananController@permintaanData')->name('permintaan-data');
Route::get('paket-data','PackageDataController@index')->name('paket-data.index');
/*
|--------------------------------------------------------------------------
| Pengembangan Profesi
|--------------------------------------------------------------------------
*/
Route::get('cmpdp/2017',function () {
	return redirect()->route('cmpdp');
});
Route::get('cmpdp','ProdukLayananController@cmpdp')->name('cmpdp');

Route::get('moduler','ProdukLayananController@moduler')->name('moduler');
Route::get('cmk','ProdukLayananController@cmk')->name('cmk');
Route::get('rivan','ProdukLayananController@rivan')->name('rivan');
Route::get('ppl','ProdukLayananController@ppl')->name('ppl');
Route::get('sekolahreksadana','ProdukLayananController@reksadana')->name('reksadana');

/*
|--------------------------------------------------------------------------
| Akademik, Hubungi Kami & FAQ
|--------------------------------------------------------------------------
*/
// Route::get('/gratis','AkademikController@gratis')->name('gratis');
Route::get('/jadwal-kegiatan','AkademikController@jadwalKegiatan')->name('jadwal-kegiatan');
Route::get('jadwal-kegiatan/{jadwalkegiatan}/view','AkademikController@jadwalKegiatanView')->name('jadwal-kegiatan-view');
Route::get('/standar-kelulusan','AkademikController@standarKelulusan')->name('standar-kelulusan');
Route::get('/hubungi-kami','AkademikController@hubungiKami')->name('hubungi-kami');
Route::get('/faq','AkademikController@faq')->name('faq');
/*
|--------------------------------------------------------------------------
| Data Pasar Modal
|--------------------------------------------------------------------------
*/
Route::get('datapasarmodal','DataEmitenController@overview')->name('dataemiten.overview');
Route::get('dataemiten/{doctype}/{type}','DataEmitenController@index')->name('dataemiten');
Route::get('dataemiten/{doctype}/{type}/viewpdf/{emitendata}','DataEmitenController@viewpdf')->name('dataemiten.viewpdf');
Route::get('dataemiten/{doctype}/{type}/getpdf/{emitendata}','DataEmitenController@getpdf')->name('dataemiten.getpdf');
Route::get('dataemiten/{doctype}/{type}/getthumbnail/{emitendata}','DataEmitenController@getthumbnail')->name('dataemiten.gethumbnail');
Route::get('dataemiten/{doctype}/{type}/pengumuman','DataEmitenController@pengumuman')->name('dataemiten.pengumuman');
Route::get('dataemiten/{doctype}/{type}/viewpdfpengumuman/{pengumuman}','DataEmitenController@viewPengumumanPdf')->name('dataemiten.pengumuman.viewpdf');
Route::get('dataemiten/{doctype}/{type}/peraturan','DataEmitenController@peraturan')->name('dataemiten.peraturan');
Route::get('dataemiten/{doctype}/{type}/viewpdfperaturan/{peraturan}','DataEmitenController@viewPeraturanPdf')->name('dataemiten.peraturan.viewpdf');
Route::get('dataemiten/{doctype}/{type}/viewsingle/{emitendata}/{title?}','DataEmitenController@viewSingle')->name('dataemiten.viewsingle');
Route::get('datapasarmodal-lainnya','DataEmitenController@dataLainnya')->name('data-lainnya');

/**
 * Keranjang Belanja
 */

Route::get('cart/view','CartController@viewcart')->name('cart.view');
Route::post('cart/add_item','CartController@addItem')->name('cart.add');
Route::get('cart/remove_item/{id}','CartController@removeItem')->name('cart.remove');
Route::get('cart/remove_all','CartController@removeAllItem')->name('cart.removeall');
Route::post('cart/store', 'CartController@store')->name('cart.store');

/*
|--------------------------------------------------------------------------
| Pelatihan
|--------------------------------------------------------------------------
*/
Route::group(['prefix'=>'seminar'], function (){
	Route::get('{workshopslug}','WorkshopController@index')->name('pelatihan');
	Route::get('{workshopslug}/laporan','WorkshopController@workshopReport')->name('pelatihan.laporan');
//	Route::get('{workshopslug}/daftar','WorkshopController@pendaftaran')->name('pelatihan.daftar');
});


//Karir Umum
Route::get('karir_front','KarirController@karirFront')->name('karir_front');

Route::group(['middleware' => 'guest'], function (){
	// Register Peserta
	Route::post('/register/storeNonSID', 'RegisterController@storeNonSID')->name('register.storeNonSID');
	Route::get('register/success', 'RegisterController@registrationSuccess')->name('register-success');
	Route::get('/verify/{useremail}/{userid}','RegisterController@verifyRegistration')->name('register.verify');
	Route::get('register/ajax_get_kabupaten','RegisterController@ajax_get_kabupaten')->name('register.ajax_get_kabupaten');
	Route::resource('/register', 'RegisterController');

resources/views/batch.blade.php
    @if($workshops && $workshops->count() > 0)
        @foreach($workshops as $workshop)
            <div class="col-sm-3 item-batch">
                <div class="event-wrap">
                    <div class="event-img-wrap course-banner-wrap color-white text-center" style="">
                        @if($workshop->program->nama == "Forum")
                            <img alt="Event" class="img-responsive" src="{{ url('assets/images/course/new/WORKSHOP.png') }}" width="600" height="220">
                        @else
                            @if($workshop->is_online == 1)
                                <img alt="Event" class="img-responsive" src="{{ url('assets/images/course/new/ONLINE-CLASS.png') }}" width="600" height="220">
                            @else
                                <img alt="Event" class="img-responsive" src="{{ url('assets/images/course/new/WORKSHOP.png') }}" width="600" height="220">
                            @endif
                        @endif
                        <span class="cat bg-yellow">{{ $workshop->program->nama }} {{ (($workshop->is_online == 1) ? 'ONLINE':'') }}</span>
                    </div>
                    <!-- Event Detail Wrapper -->
                    <div class="event-details" style="height: 450px;">
                        <h4 class="batch-title" style="font-size: 16px;">
                            @if($workshop->is_online == 1)
                                <a href="https://ticmi.co.id/kelas-online/{{ $workshop->slugs }}" onclick="ga('send', 'event', 'Pendaftaran Online Class', '{{ $workshop->workshop_name }}', '{{ url()->current() }}' )">{{ $workshop->workshop_name }}</a>
                            @else
                                <a href="https://ticmi.co.id/seminar/{{ $workshop->slugs }}" onclick="ga('send', 'event', 'Pendaftaran Workshop', '{{ $workshop->workshop_name }}', '{{ url()->current() }}' )">{{ $workshop->workshop_name }}</a>
                            @endif
                        </h4>
                        @if($workshop->is_online == 0)
                            <ul class="events-meta">
                                <li><i class="fa fa-calendar-o"></i>{{ strftime('%A, %#d %B %Y',strtotime($workshop->tgl_mulai)) }}</li>
                                <li><i class="fa fa-map-marker"></i>{{ $workshop->program->nama }}</li>
                                <li><i class="fa fa-users"></i> {{ $workshop->waktu }}</li>
                            </ul>
                        @else
                            <ul class="events-meta">
                                <li><i class="fa fa-map-marker"></i>http://elearning.ticmi.co.id</li>
                                <li><i class="fa fa-clock-o"></i>Periode Akses : {{ $workshop->lama_belajar }} Hari</li>
                            </ul>
                        @endif
                        <p>{!! substr(strip_tags($workshop->deskripsi),0,200) !!}</p>
                        @if($workshop->is_online == 1)
                            <a href="https://ticmi.co.id/kelas-online/{{ $workshop->slugs }}" onclick="ga('send', 'event', 'Pendaftaran Online Class', '{{ $workshop->workshop_name }}', '{{ url()->current() }}' )" class="btn"><i class="fa fa-angle-double-right"></i> Saya ingin daftar</a>
                        @else
                            <a href="https://ticmi.co.id/seminar/{{ $workshop->slugs }}" onclick="ga('send', 'event', 'Pendaftaran Workshop', '{{ $workshop->workshop_name }}', '{{ url()->current() }}' )" class="btn"><i class="fa fa-angle-double-right"></i> Saya ingin daftar</a>

                        @endif
                    </div><!-- Event Meta -->
                </div>
            </div>
        @endforeach
    @endif

    <div class="clearfix"></div>

    @if($programs && $programs->count() > 0)
       
            @foreach($programs as $key => $program)
                <!-- Event Column -->
                    <!-- Event Wrapper -->
                    @if($program->batch_publish->count() > 0)
                        <div id="{{$program->kode}}" >
                            @foreach($program->batch_publish as $key => $batch)
                                <div class="item">
                                    <div class="event-wrap">
                                        <div class="event-img-wrap course-banner-wrap color-white text-center" style="">
                                           <img alt="Event" class="img-responsive" src="{{ $batch_path.$batch->logo }}" width="600" height="220">

                                            <span class="cat bg-yellow">{{ $batch->program->kode }}</span>
                                        </div>
                                        <!-- Event Image Wrapper -->
                                        <!-- Event Detail Wrapper -->
                                        <div class="event-details" style="height: 450px;">
                                            <h4 class="batch-title" style="font-size: 16px;"><a href="{{ url('daftar-batch/'.$batch->batch_id.'/'.$batch->nama) }}" onclick="ga('send', 'event', 'Pendaftaran Sertifikasi', '{{ $batch->nama }}', '{{ url()->current() }}' )">{{ $batch->nama }} </a></h4>
                                            <ul class="events-meta">
                                                <li><i class="fa fa-calendar-o"></i>{{ strftime('%A, %#d %B %Y',strtotime($batch->tgl_mulai)) }}</li>
                                                {{--<li><i class="fa fa-calendar-o"></i> {{ date('l, d M Y',strtotime($batch->tanggal)) }}</li>--}}
                                                <li><i class="fa fa-map-marker"></i> {{ !empty($batch->lokasi->nama) ? $batch->lokasi->nama:"Gedung Bursa Efek Indonesia" }}</li>
                                                <li><i class="fa fa-users"></i> Minimal Peserta {{ !empty($batch->minimal) ? $batch->minimal:10 }} Orang</li>
                                            </ul>
                                            <p>{!! substr($batch->keterangan,0,150) !!}</p>

                                            <a href="{{ url('daftar-batch/'.$batch->batch_id.'/'.$batch->nama) }}" class="btn"><i class="fa fa-angle-double-right"></i> Saya ingin daftar</a>
                                            

                                            {{--@if($value->kd_type != 1)--}}
                                                {{--<a href="http://akademik.ticmi.co.id/index/daftar{{ $value->kd_type }}/{{ $value->id }}/Pendaftaran {{ $value->nama }}.html" class="btn">Saya ingin daftar</a>--}}
                                            {{--@else--}}
                                                {{--<a href="http://akademik.ticmi.co.id/index/daftar/{{ $value->cabang }}/{{ $value->id }}/Pendaftaran {{ $value->nama }}.html" class="btn">Saya ingin daftar</a>--}}
                                            {{--@endif--}}
                                        </div><!-- Event Meta -->
                                        <br/>
                                    </div><!-- Event details -->
                                </div><!-- Column -->
                            @endforeach
                        </div>
                    @endif

            @endforeach
    @endif

    @if($workshops->count() == 0 && $programs->count() == 0)
        <div class="col-sm-12">
            <div class="alert alert-warning" role="alert"><h4>Maaf, belum ada jadwal tersedia.</h4></div>
        </div>
    @endif

        {{-- Memasukkan array kode ke dalam select yang isinya akan diambil jquery --}}
    <select id="kode" style="visibility: hidden;">
        @foreach($arr_kode as $kode)
        <option value="{{$kode}}"></option>
        @endforeach
    </select>
    <script type="text/javascript">
        $(document).ready(function(){
            var array = [];
            $('#kode option').each(function() {
                array.push($(this).val());
            });
            
            $.each(array,function(key,val){
                $("#"+val).owlCarousel({
                    items:4,
                    nav:true,
                    margin:20,
                });
            })
        })
    </script>

resources/views/login.blade.php
@extends('layouts.base')
    @section('content')
<style>
.login {

    background: 
    /* top, transparent red, faked with gradient */ 
    linear-gradient(
      rgba(255,255,255,.7), 
      rgba(255,255,255,.7)
    ), url({{ asset('assets/ticmi/images/ticmi/library-ticmi-small.jpg') }});    
    background-position: center;
    background-repeat: no-repeat;
    background-size: 1300px 1300px;  /*cover*/
}
.login .logo {
    text-align: left;
}
</style>
<div class="page-header typo-dark" style="background: url('https://ticmi.co.id/assets/images/banner/profile.jpg') top">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- Page Header Wrapper -->
                    <div class="page-header-wrapper">
                        <!-- Title & Sub Title -->
                        <h3 class="title">Login</h3>
                    </div><!-- Page Header Wrapper -->
                </div><!-- Coloumn -->
            </div><!-- Row -->
        </div><!-- Container -->
    </div>
        <div class="logo">
            <!-- nothing here -->
        </div>
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
            <form class="login-form" role="form" action="{{ route('login') }}" method="post" id="form_login">
                {{ csrf_field() }}
                <center>
                    <img src="{{ asset('assets/theme/global/img/logo-ticmi.png') }}" class="logo-default" width="150" alt="logo">
                </center>
                <br>
                <br>
                @if(Session::has('alert-error'))
                <div class="alert alert-danger alert-dismissible" role="alert">
                    {!! Session::get('alert-error') !!}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                @endif
                @if(Session::has('message'))
                        <div class="alert {{ Session::get('alert-class') }} alert-dismissible" role="alert">
                            {!! Session::get('message') !!}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                    @endif
                <div class="form-group">
                    <label for="email" class="control-label visible-ie8 visible-ie9">Email</label>
                    <input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" value="{{ old('username') }}" required autofocus/>
                    @if ($errors->has('email'))
                        <span class="help-block" style="color:red">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Password</label>
                    <input id="password" class="form-control form-control-solid placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password" required/>
                    @if ($errors->has('password'))
                        <span class="help-block" style="color:red">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                    <a class="pull-right" href="{{ route('forgot_password') }}">(Lupa Password?)</a>
                </div>
                <div class="form-actions">
                    <span id="execute-loading" style="display: none;"><img src="{{ asset('assets/theme/global/img/loading.gif') }}"></span>
                    <button type="submit" name="login" class="btn green uppercase">Login</button>
                    <div class="pull-right" style="padding-top: 0px!important; text-align: right;">
                        Belum punya akun ?<br>
                        <a class="green" href="{{ route('register.index') }}">Silahkan Daftar</a>
                    </div>
                </div>
                <br>
                <br>
                <div class="create-account">
                <!-- nothing here -->
                </div>
            </form>
            <!-- END LOGIN FORM -->
        </div>
        <div class="copyright"> 2017 © TICMI</div>

{!! JsValidator::formRequest('App\Http\Requests\LoginRequest', '#form_login'); !!}
{{-- <script type="text/javascript" src="{{ asset('js/js.cookie.min.js') }}"></script>

    <script>
        $(document).ready(function(){
            
            var cookies = Cookies.get();
            for(var cookie in cookies) {
               Cookies.remove(cookie);
            }
            console.log(Cookies.get());
        });
    </script>    --}}
    <script type="text/javascript">
        /**
        * Action before submit form
        */
        $('#form_login').on('submit', function (e) {
            // form is valid
            is_form_valid = $('#form_login').valid();
            if(is_form_valid == true){
                $('button[name="login"]').attr('disabled', 'disabled');
                $('#execute-loading').css({'display': 'block'});
            }
        });
    </script>

<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/5b3aef6c6d961556373d5962/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
    })();
</script>
<!--End of Tawk.to Script-->
@endsection

resources/views/maintenance.blade.php
<!DOCTYPE html>
<!--[if IE 8 ]><html class="no-js oldie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->

<head>

	<!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>TICMI | Maintenance</title>
   <meta name="description" content="">  
   <meta name="author" content="">

   <!-- Mobile Specific Metas
   ================================================== -->
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

   <!-- CSS
   ================================================== -->
   <link rel="stylesheet" href="https://ticmi.co.id/assets/css_um/base.css">
   <link rel="stylesheet" href="https://ticmi.co.id/assets/css_um/vendor.css">
   <link rel="stylesheet" href="https://ticmi.co.id/assets/css_um/main.css">    

   <!-- Modernizr
   =================================================== -->
   <script src="js/modernizr.js"></script>

   <!-- Favicons
   =================================================== -->
   <link rel="shortcut icon" href="https://ticmi.co.id/assets/favicon.png" >
    
</head>
    
<body>

   <!--[if lt IE 9]>
   	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. 
   	Please <a href="https://ticmi.co.id/assets/http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
   <![endif]-->   

   <!-- content-wrap -->
   <div id="content-wrap">

      <!-- main  -->
      <main class="row">

            <header class="site-header">
               <div class="logo">
               	<a href="https://ticmi.co.id/assets/index.html">Advent.</a>
               </div> 
            </header>

            <div id="main-content" class="twelve columns">

               <h1>This website is under construction</h1>

               <p> Estimated time remaining before launch
               </p>

               <hr>

               <div id="counter" class="group">
                  <span>0 <em>days</em></span> 
                  <span>2 <em>hours</em></span>
                  <span>00 <em>minutes</em></span>
                  <span>00 <em>seconds</em></span> 
               </div>                  

               <!-- MailChimp Signup Form -->
                

            </div><!-- /main-content form -->

             
            
      </main>	      

   </div><!-- /content-wrap --> 
    	

   <!-- modals
   =================================================== -->
	      
	 

    

 	<!-- footer
   =================================================== -->
    

   <div id="preloader"> 
    	<div id="loader">
     	</div>
   </div> 
   
<!-- Script
=================================================== -->
<script src="https://ticmi.co.id/assets/js_um/jquery-1.11.3.min.js"></script>
<script src="https://ticmi.co.id/assets/js_um/jquery-migrate-1.2.1.min.js"></script>
<script src="https://ticmi.co.id/assets/http://maps.google.com/maps/api/js_um?v=3.13&amp;sensor=false"></script>    
<script src="https://ticmi.co.id/assets/js_um/jquery.fittext.js"></script>
<script src="https://ticmi.co.id/assets/js_um/jquery.countdown.min.js"></script>
<script src="https://ticmi.co.id/assets/js_um/jquery.placeholder.min.js"></script>
<script src="https://ticmi.co.id/assets/js_um/owl.carousel.min.js"></script>
<script src="https://ticmi.co.id/assets/js_um/jquery.ajaxchimp.min.js"></script>
<script src="https://ticmi.co.id/assets/js_um/main.js"></script>    
        
</body>
</html>

resources/views/verify-email.blade.php
@extends('layouts_ticmi.home')
@section('content')

    <!-- Page Main -->
    <div class="page-default bg-grey typo-dark">
        <!-- Container -->
        <div class="container">

            <div class="row shop-forms">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 content-box shadow bg-white">
                            <ul class="text-center">
                                <!-- Page Template Logo -->
                                <li class="logo-wrap">
                                    <a href="" class="logo">
                                        <h5>Verifikasi Email</h5>
                                    </a>
                                </li><!-- Page Template Logo -->
                            </ul>
                            @if(Session::has('verified'))
                                <div class="alert {{ Session::get('alert-class') }}">{{ Session::get('verified') }}</div>
                            @else
                                @if(Session::has('message'))
                                    <div class="alert {{ Session::get('alert-class') }}">{{ Session::get('message') }}</div>
                                @endif
                                    {{ Form::open(['url'=>route('register.resend-email-verification.proses')]) }}
                                    <div class="input-text form-group text-left">
                                        {!! Form::email('email',null,['class'=>'input-name form-control','placeholder'=>'Masukkan Email Anda', 'required']) !!}
                                        <small class="form-note">Cek kembali Email Anda, pastikan email yang Anda masukkan benar</small>
                                    </div>
                                    {!! Form::submit('Verifikasi Email',['class'=>'btn btn-block','data-loading-text'=>'Loading ...','data-toggle'=>'loading','data-confirm'=>'false']) !!}
                                    {{ Form::close() }}
                            @endif
                            <br>
                            <br>
                            <ul class="text-center">
                                <li>
                                    Kembali ke halaman <a href="{{ route('login') }}">Login</a> atau <a href="{{ route('register.index') }}">Daftar</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!-- Row -->

        </div><!-- Container -->
    </div><!-- Page Default -->
    <!-- Page Main -->


@endsection

resources/views/wisuda.blade.php
<iframe src="https://old.ticmi.co.id/wisuda/2018" style="border:0px #ffffff none;" name="myiFrame" scrolling="no" frameborder="1" marginheight="0px" marginwidth="0px"   height="250%" width="100%" allowfullscreen></iframe>